version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - tree
  jobs:
    post_build:
      - echo "Command run at 'post_build' step"
      - echo `date`
      - bash install.sh
