version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - tree
  jobs:
    pre_build:
      - bash test.sh
    post_build:
      - echo "Command run at 'post_build' step"
      - echo `date`
      - bash install.sh
sphinx:
  builder: html
  configuration: doc/main/conf.py
  fail_on_warning: false
