version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - tree
  jobs:
    pre_build:
      - bash show.sh
sphinx:
  builder: html
  configuration: doc/main/conf.py
  fail_on_warning: false
